### ISSUE TITLE
It seems that there's not a "ReLU" stage implemented ?

### ISSUE THREAD

**Issue by lr87** [jonathantompson/jtorch#6] opened 2017-01-03 01:57 UTC
I can't find "ReLU" stage in the code, while this stage is necessary for most networks. So, I'm wondering if the author can add the implementation.

And also, better explanation for how to use the forward pass is needed. Thanks a lot !

**Comment by jonathantompson** [comment] 2017-01-04 00:24
To your first request: ReLU is just a Threshold with [0, 0] as the parameters. It is already "implemented":

https://github.com/jonathantompson/jtorch/blob/06263b3f45552937c7ac2f3a59e4d59ae92c1ba2/lua/save_nn_node.lua#L66

i.e. when saving out the torch model in lua, ReLU stages are dumped to disk as Threshold stages.

If you want a ReLU implementation in C++, feel free to create a class that extends Threshold but specifies the value and threshold values and submit a PR.  I probably wont add it because it'll be redundant.

To you second request: I still need to add more documentation and this request has already been made (i.e. duplicate of issue #5). So I'll close this issue and you can refer to that thread.

**Closed as completed by jonathantompson** 2017-01-04 00:24 UTC
